reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:index, :new] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]

  root to: 'sessions#new'
end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  moderator_id :integer
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    class_name: "User",
    foreign_key: "moderator_id",
    primary_key: "id"

  has_many :posts,
    through: :post_subs,
    source: :sub

  has_many :post_subs,
    class_name: "PostSub",
    foreign_key: "sub_id",
    primary_key: "id"
end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_moderator, only: [:edit]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Something went wrong"]
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = ["Something went wrong"]
      render :edit
    end
  end

  private

    def sub_params
      params.require(:sub).permit(:title, :description)
    end

    def ensure_moderator
      @sub = Sub.find(params[:id])

      redirect_to user_url(current_user) unless current_user.id == @sub.moderator_id
    end
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/views/subs/_form.html.erb
<% action_url = (@sub.persisted? ? sub_url(@sub) : subs_url ) %>
<% method = (@sub.persisted? ? "PATCH" : "POST" ) %>
<% submit_value = (@sub.persisted? ? "Edit Sub" : "New Sub" ) %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <label>Title</label>
  <input type="text"
         name="sub[title]"
         value="<%= @sub.title %>">
  <br>
  <br>

  <label>Description</label>
  <input type="text"
         name="sub[description]"
         value="<%= @sub.description %>">
  <br>

  <input type="submit" value="<%= submit_value %>">
</form>

reddit_clone/app/views/subs/_posts.html.erb
<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <%= link_to post.title, post_url(post) %>
    </li>
  <% end %>
</ul>

reddit_clone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>
<%= render partial: 'form' %>

reddit_clone/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render partial: 'form' %>

reddit_clone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p><%= @sub.description %></p>
<%= render partial: 'posts' %>

<% if current_user.id == @sub.moderator_id %>
  <%= link_to "Edit Sub", edit_sub_url %>
<% end %>
<%= link_to "Create Post for this Sub", new_sub_post_url(@sub) %>