music_app/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create, :update, :destroy] do
    member do
      get 'activate'
    end
  end
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index] do
    resources :notes, only: [:new]
  end

  resources :notes, except: [:new]

  root to: redirect('session/new')
end

music_app/app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums,
    class_name: "Album",
    foreign_key: "band_id",
    primary_key: "id",
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :check_login
  
  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url
    else
      flash.now[:errors] = ['Something went wrong']
      render :new
    end
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])

    render :show
  end

  def destroy
    @band = Band.find(params[:id])

    @band.destroy
    redirect_to bands_url
  end

  private

    def band_params
      params.require(:band).permit(:name)
    end
end

music_app/app/helpers/bands_helper.rb
module BandsHelper
end

music_app/app/views/bands/_albumlist.html.erb
<ul>
  <% @band.albums.each do |album| %>
    <li><%= link_to album.title, album_url(album) %></li>
  <% end %>
</ul>

music_app/app/views/bands/_form.html.erb
<% method_name = (@band.persisted? ? "PATCH" : "POST") %>
<% action_url = (@band.persisted? ? band_url(@band) : bands_url) %>

<form action='<%= action_url %>' method='POST'>
  <input type='hidden' name='_method' value='<%= method_name %>'>
  <%= auth_token %>

  <label>Band Name</label>
  <input type='text' name='band[name]' value='<%= @band.name %>'>

  <input type='submit' value='Submit'>
</form>

music_app/app/views/bands/edit.html.erb
<%= render partial: 'form' %>

music_app/app/views/bands/index.html.erb
<h1>List of Bands</h1>
<%= link_to 'Create a Band', new_band_url %>
<ul>
  <% @bands.each do |band| %>
    <li><%= link_to band.name, band_url(band) %></li>
  <% end %>
</ul>

music_app/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<br>
<h3>Albums</h3>
<%= render partial: 'albumlist' %>
<%= link_to 'Create an Album', new_band_album_url(@band) %>
<br>

<%= link_to 'Edit Band', edit_band_url(@band) %>
<br>

<%= button_to 'Delete Band', band_url(@band), method: :delete %>

<%= link_to 'Back', bands_url %>