reddit_clone/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end

  resources :posts, except: [:index, :new] do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]

  root to: 'sessions#new'
end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :username, :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs,
    class_name: "Sub",
    foreign_key: "moderator_id",
    primary_key: "id"

  has_many :posts,
    class_name: "Post",
    foreign_key: "author_id",
    primary_key: "id"

  has_many :comments,
    class_name: "Comment",
    foreign_key: "author_id",
    primary_key: "id"

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    save!
    session_token
  end

  private

    def ensure_session_token
      self.session_token ||= SecureRandom.urlsafe_base64(16)
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_login, only: [:show]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!
    else
      flash.now[:errors] = "Invalid username / password combo"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @subs = Sub.all

    render :show
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end

    def check_login
      @user = User.find(params[:id])
      redirect_to user_url(current_user) unless @user == current_user
    end
end

reddit_clone/app/views/users/_subs.html.erb
<ul>
  <% @subs.each do |sub| %>
    <li>
      <%= link_to sub.title, sub_url(sub) %>
    </li>
  <% end %>
</ul>

reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST" >
  <%= auth_token %>
  <label for="Username">Username:</label>
  <input type="text" name="user[username]" id="Username">
  <br>
  <br>

  <label for="Password">Password:</label>
  <input type="password" name="user[password]" id="Password">
  <br>
  <br>

  <input type="submit" value="Sign Up">
</form>

reddit_clone/app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %></h1>

<%= render partial: 'subs' %>